name: ci

on:
  push:
    branches: [master, main, develop]
  pull_request:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: npm-cache-ubuntu-latest-node@20

      - uses: pnpm/action-setup@v2

      - name: 'Install dependencies'
        run: pnpm install

      - name: Build TypeScript
        run: |
          pnpm build

      - name: Publish NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}